name: CI Back-end

on: #esse wokflow executa com o push e o pull_requets
  push:
    branches:
      - 'main' #ou quando faz um push direto no main
    paths:
      - 'back-end/**'
  pull_request:
    paths:
      - 'back-end/**' #ou quando faz um pull no back end
  workflow_call: #ou quando é chamado de outro workflow
  
jobs:
  testes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Compilação / Test / Package
        working-directory: back-end/
        run: mvn --activate-profiles prod test
  criar:
    needs: testes #fala que só roda com o de cima
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Compilação / Test / Package
        working-directory: back-end/
        run: mvn --activate-profiles prod -DskipTests package
