name: CI Back-end Branches

on:
  push:
    branches:
      - '**'
      - '!main'
    paths:
      - 'back-end/**'

jobs:

  main:
    name: CI Workflow Main
    uses: ./.github/workflows/ci-backend-main.yml #é tipo um import, ele chama
    
  merge:
    needs: main #só inicia com o main concluido
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Merge branch
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          target_branch: main #ramo de destino, em qual ramo faz o merge, no caso o main
          github_token: ${{ github.token }} #pra dar acesso ao nosso repositorio
    
    
